export enum Estado {
  PENDIENTE=<any>'PENDIENTE',
  CONSUMIDO=<any>'CONSUMIDO',
  FACTURADO=<any>'FACTURADO',
  CANCELADO=<any>'CANCELADO',
  ENVIADO_RIESGO=<any>'ENVIADO_RIESGO',
  RECIBIDO_RIESGO=<any>'RECIBIDO_RIESGO',
  ENVIADO_BANCO=<any>'ENVIADO_BANCO',
  RECHAZADO=<any>'RECHAZADO',
  PARA_RECTIFICAR=<any>'PARA_RECTIFICAR',
  CONCILIADO=<any>'CONCILIADO',
  REENVIADO=<any>'REENVIADO',
  ANULADO=<any>'ANULADO',
  INICIAL=<any>'INICIAL',
  PAGADO=<any>'PAGADO'
}
